#!/bin/bash
cd $(cd $(dirname $0); pwd)
echo -e '\e[1m\e[31m
Storm source is being installed, 
Please wait until the installation is complete
\033[0m'
echo -e '\033[0;33m
If it is the first time to install the source, send the number » {1}
or اذا كانت اول مره تنصيب السورس ارسل رقم » {1}
If you have already installed the source, send the number » {2}
or اذا سبق ونصبت السورس ارسل رقم » {2}
\033[0m'
read Install
case $Install in
1)
echo -e '\033[0;33mOffice installation has begun'
sleep 2

# تحديث النظام وتثبيت الحزم الأساسية
sudo yum update -y
sudo yum upgrade -y
sudo yum install -y \
  lua \
  wget \
  tmux \
  screen \
  zip \
  readline-devel \
  libconfig-devel \
  openssl-devel \
  lua-socket \
  lua-sec \
  lua-expat \
  libevent-devel \
  make \
  unzip \
  git \
  redis \
  autoconf \
  gcc-c++ \
  jansson-devel \
  python3-devel \
  expat-devel \
  python3 \
  python3-pip \
  gnome-calculator \
  libconfig++-devel \
  libstdc++-devel \
  lua-lgi \
  software-properties-common \
  libnotify-devel \
  lua-space \
  ffmpeg

# تثبيت luarocks والإضافات
wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
tar zxpf luarocks-2.4.3.tar.gz
cd luarocks-2.4.3
./configure
make
sudo make bootstrap
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install luautf8
sudo luarocks install redis-lua
sudo luarocks remove lua-cjson2
sudo luarocks remove lua-cjson
sudo yum install -y lua-cjson
sudo luarocks install Lua-cURL
cd ..

# إعادة تثبيت إصدار أقدم من luarocks
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz
tar zxpf luarocks-2.2.2.tar.gz
cd luarocks-2.2.2
./configure
sudo make bootstrap
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install lua-term
sudo luarocks install Lua-cURL
cd ..

# بدء خدمة redis
sudo systemctl start redis

# تثبيت مكتبات Python
python3 -m pip install -U pip setuptools yt-dlp ffmpeg gtts nsfw-detector opencv-python

# تنظيف الملفات المؤقتة
rm -rf luarocks*

# فك ضغط الملفات وتنفيذ السكربت
unzip tdlua.zip
sudo mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.2/tdlua.so
rm -fr tdlua.zip
sudo lua Fast.lua
;;

2)
echo -e "\e[1m\e[32mThe bot is running now : جاري تشغيل البوت الان : \e[0m"
sleep 2

# فك ضغط الملفات وتنفيذ السكربت
unzip tdlua.zip
sudo mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.2/tdlua.so
rm -fr tdlua.zip
sudo lua Fast.lua
;;
esac
